---
title: "Taller 1"
output: html_notebook
---

```{r}
library("MTS")
library("xts")
library("zoo")
```

# Pressure Readings at Both Ends of the Furnace

```{r}
pressure <- read.csv("pressure.csv", header = T, sep=",")
attach(pressure)
head(pressure)
```

The pressure readings at two ends of an industrial furnace are taken every ten minutes

```{r}
par(mfrow = c(2,1))
plot(index,front, type="l", main = "Pressure Readings at Both Ends of the Furnace",xlab="Sampling each (10 min)",ylab="Front", cex.main = 0.8)
points(index,front,pch = 1)

plot(index, back, type="l",ylab="Back",xlab="Sampling each (10 min)", cex.main = 0.8)
points(index,back,pch = 1)
```

```{r}

covfront <- c(1,cov(front,back))
covback <- c(cov(front,back),1)
pre_cov<- as.table(rbind(covfront,covback))
rownames(pre_cov) <- c("front","back")
colnames(pre_cov) <- c("front","back")
print("Matriz de Covariables")
print("---------------------")
pre_cov
```
```{r}
# Covariance of the time 0

co <- function(vector){
  
  Co <- c()
  yHat <- mean(vector)
  for (i in 1:length(vector)){
  
    Co[i] <- (vector[i]-yHat)*(vector[i]-yHat)
  
  }
  
  Co <- sum(Co)/length(vector)
  Co <- round(Co, 4)
  
  return (Co)
  
}
```


```{r}
# ACF autocorrelation function

ACF <- function(vector,kend = 25){
  
  yHat <- mean(vector)
  Co <- co(vector)
  
  cov_vector <- c()
  rn <- c()
  
  for ( i in 1:kend){
    
    Cn <- c()
    
    for (j in 1:(length(vector)-i)){
  
      Cn[j] <-(vector[j]-yHat)*(vector[j+i]-yHat)
      
    }
    cov_vector[i]<- sum(Cn)/length(vector)
    rn[i] <- cov_vector[i]/Co
  }
  
  #cov_vector < round(cov_vector,4)
  #rn <- round(rn,4)
  result <- data.frame(cov_vector,rn)
  return(result)
  
  
}

```

```{r}
acf <- ACF(front, kend = length(front))
```


```{r}
library(dplyr)
library(ggplot2)

ggplot(acf, aes(x = seq(1:length(front)), y = rn)) +
  geom_col(position = "identity") + 
  ggtitle("ACF") +
  xlab("Lag, K") + ylab("Autocorrelation, rk")

```


```{r}
stocks <- read.csv("stocks.csv", sep=",")
head(stocks)
```

```{r}
MTSplot(stocks)
```


```{r}
cor(stocks)
```
```{r}
cor(stocks, method = "spearman")
```
```{r}
pairs(stocks)
```


```{r}
pairs(stocks, lower.panel = NULL, main = "Stocks Correlation Scatterplots")
```

```{r}
require(corrplot)
corrplot(cor(stocks), method = "number")
```

